[buildpack]
id = "genericlawcoder/python-pyodbc-buildpack"
name = "Python ODBC heroku buildpack"
version = "1.0.0"
api = "0.2"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.focal"
