api = "0.9"

[buildpack]
id = "genericlawcoder/python-pyodbc-buildpack"
name = "Python ODBC heroku buildpack"
version = "2.1.1"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.focal"
